### PR TITLE
pb/github actions

### PR DESCRIPTION
**Pull request by pbrisbin**
- Migrate to GitHub Actions
- Use stable order for available-upgrade names
- Add FIXTURES_DEBUG support
- Track last-access in fixtures directory
- Update fixtures

### CODE REVIEW

**Comment by pbrisbin** [comment]
:thinking: Need to figure out how to prevent it running twice.

**Comment by aragon999** [comment]
Mh, that is something really annoying. Unfortunately I really do not know a way except to only run on for example the `main`-branch and on pull requests. If you want that I can provide you with a fix for that.

Thank you for finishing the task :-)

Btw. you might want to rebase the branch onto my pull request, I am not sure but I think that then when merging both PRs should be closed.

**Comment by pbrisbin** [comment]
Yeah, I was expecting to merge this PR and close yours without merging (sorry!).

I think `push: { branches: [main] }` and `pull_request:` is actually what I want! I'll try that.

**Comment by filipesperandio** [comment]
Hahaha master => main just broke our builder's build.

**Comment by pbrisbin** [comment]
@filipesperandio Amazing, that's hilarious.

**Pull request merged**
