### PR TITLE
Fixed RPCv5 URLs

### PR DESCRIPTION
**Pull request by inalelbeyli**
Wasn't getting any package results. Fixed the AUR search & info URLs to the v5 versions per: [https://aur.archlinux.org/rpc.php](https://aur.archlinux.org/rpc.php)

### CODE REVIEW

**Comment by pbrisbin** [comment]
Strange, is this a recent change? Since the big migration?

I'll get the tests in order and commit as soon as I can. Thanks!

**Comment by pbrisbin** [comment]
Opened along with test fixes as #44. Will merge on green and release as soon as I can.

**Comment by inalelbeyli** [comment]
I think it's fairly recent - it stopped working for me with Pacman 5.0.1. Thanks for the test updates, I'll keep my eyes out for the release!

**Comment by pbrisbin** [comment]
Merged as e0dc328

**Comment by inalelbeyli** [comment]
Awesome, thanks!!

**Pull request closed without merging**
